[phases.setup]
nixPkgs = ["python312", "tesseract", "ffmpeg", "libGL"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python main.py"
